patches-source = "mvaishak/letterboxd-morphe-patches"
brand = "mvaishak"

[Letterboxd-mvaishak]
enabled = true
pkg-name = "com.letterboxd.letterboxd"
app-name = "Letterboxd"
included-patches = "'Appearance' 'Brighter Watched-by stars' 'Denser poster grid' 'Hide ads' 'Mod settings'"
excluded-patches = "'Material You theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/letterboxd-limited/letterboxd"
uptodown-dlurl = "https://letterboxd.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/letterboxd/com.letterboxd.letterboxd"
apkcombo-dlurl = "https://apkcombo.com/letterboxd/com.letterboxd.letterboxd"
