[PocketWhip-hxreborn]
enabled = true
pkg-name = "com.greenstone.pocketwhip"
app-name = "Pocket Whip"
patches-source = "hxreborn/morphe-patches"
brand = "hxreborn"
uptodown-dlurl = "https://com-greenstone-pocketwhip.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/pocket-whip-original-whip-app/com.greenstone.pocketwhip"
apkcombo-dlurl = "https://apkcombo.com/pocket-whip-original-whip-app/com.greenstone.pocketwhip"